# Generated by Django 4.2.7 on 2023-12-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="spotifyid",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="spotifyurl",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
