# Generated by Django 4.2.7 on 2023-12-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0002_podcast_spotifyid_podcast_spotifyurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="spotifyimg",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
