# Generated by Django 4.2.7 on 2023-11-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0002_tag_review_podcast_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="vote_ratio",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="podcast",
            name="vote_total",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
