# Generated by Django 4.2.7 on 2023-12-03 21:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0003_podcast_spotifyimg"),
    ]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                ("title", models.CharField(max_length=400)),
                ("description", models.TextField(blank=True, null=True)),
                ("spotifyid", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "spotifyurl",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                (
                    "spotifyimg",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("release_date", models.CharField(max_length=30)),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, default="default.jpg", null=True, upload_to=""
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("vote_total", models.IntegerField(blank=True, default=0, null=True)),
                ("vote_ratio", models.FloatField(blank=True, default=0, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
