# Generated by Django 4.2.7 on 2023-11-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile_username"),
        ("podcasts", "0004_podcast_featured_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="podcast",
            options={"ordering": ["-vote_total", "-vote_ratio"]},
        ),
        migrations.RenameField(
            model_name="review",
            old_name="rating",
            new_name="value",
        ),
        migrations.AddField(
            model_name="review",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("owner", "podcast")},
        ),
    ]
