# Generated by Django 4.2.7 on 2023-12-03 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0004_episode"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="podcast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="podcasts.podcast",
            ),
        ),
    ]
