# Generated by Django 4.2.7 on 2023-12-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0006_reviewepisode"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="spotifyimg2",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="reviewepisode",
            name="episode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewsEpisode",
                to="podcasts.episode",
            ),
        ),
    ]
