# Generated by Django 4.2.7 on 2023-12-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0007_podcast_spotifyimg2_alter_reviewepisode_episode"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="duration",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="episode",
            name="spotifyimg2",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
