# Generated by Django 4.2.7 on 2023-12-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("podcasts", "0008_episode_duration_episode_spotifyimg2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="episode",
            options={"ordering": ["-release_date"]},
        ),
        migrations.AddField(
            model_name="episode",
            name="description_html",
            field=models.TextField(blank=True, null=True),
        ),
    ]
